twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        application: '@App\Application\Twig\GlobalApplication'
    date:
        timezone: Africa/Tunis
